
<h2 style="
background-color:#F8D7DA;
color:black;
padding:10px;
border-radius:8px;
font-weight:bold;
font-style:italic;
">
Task 1 : Data Cleaning and Formatting
</h2>

In [3]:
# Import the jp morgan cs file
df= pd.read_csv(r"C:\Users\rahul\OneDrive\Desktop\Python\Python Data\jp_morgan.csv")

In [ ]:
import pandas as pd
import numpy as np

In [4]:
print("=" * 60)
print("Dataset Preview")
print("=" * 60)

# Display the first five rows of the DataFrame
df.head()

============================================================
Dataset Preview
============================================================

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,3,CUST2412,ACC80131,Loan,Withdrawal,Personal Loan,Firm C,West,Manager 3,06-08-2023,33759.69057,126486.40830,0.225824,611,89
1,32,CUST1467,ACC74631,Current,Withdrawal,Home Loan,Firm D,North,Manager 2,08-11-2023,69319.19933,24834.76291,0.335717,817,174
2,9,CUST2699,ACC39482,Loan,Withdrawal,Credit Card,Firm D,West,Manager 4,15-05-2024,42831.48483,123007.43530,0.572453,332,31
3,42,CUST9535,ACC82947,Current,Withdrawal,Home Loan,Firm A,South,Manager 4,30-04-2023,70903.79697,73073.64225,0.571993,626,92
4,166,CUST7459,ACC39500,Credit,Payment,Home Loan,Firm D,South,Manager 4,16-02-2023,21948.97355,113405.32820,0.380675,411,13

In [5]:
df.describe()

,TransactionID,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
count,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,101.96125,51086.624542,74528.005025,0.473350,576.303750,123.566250
std,58.27147,29076.621451,32608.264579,0.245104,160.816133,66.426755
min,1.00000,-60979.073480,-13812.693060,-0.368537,304.000000,6.000000
25%,49.00000,32589.042120,53547.221090,0.305702,433.000000,67.000000
50%,104.00000,50307.224210,73736.442995,0.461838,573.000000,123.000000
75%,155.25000,70179.479290,95584.413473,0.634402,722.000000,181.000000
max,199.00000,147447.295100,183836.933800,1.345638,849.000000,239.000000

<h3 style="color:blue;">1.1 Remove/treat any special characters and non-numeric entries from financial fields.</h3>

####  This cleans the financial data and keeps only numeric values for calculations
#### pd.to_numeric() converts values into numbers (int/float) so we can perform calculations

In [9]:

df["TransactionAmount"] = df["TransactionAmount"].replace('[₹,]', '', regex=True)
df["AccountBalance"] = df["AccountBalance"].replace('[₹,]', '', regex=True)
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,3,CUST2412,ACC80131,Loan,Withdrawal,Personal Loan,Firm C,West,Manager 3,06-08-2023,33759.69057,126486.40830,0.225824,611,89
1,32,CUST1467,ACC74631,Current,Withdrawal,Home Loan,Firm D,North,Manager 2,08-11-2023,69319.19933,24834.76291,0.335717,817,174
2,9,CUST2699,ACC39482,Loan,Withdrawal,Credit Card,Firm D,West,Manager 4,15-05-2024,42831.48483,123007.43530,0.572453,332,31
3,42,CUST9535,ACC82947,Current,Withdrawal,Home Loan,Firm A,South,Manager 4,30-04-2023,70903.79697,73073.64225,0.571993,626,92
4,166,CUST7459,ACC39500,Credit,Payment,Home Loan,Firm D,South,Manager 4,16-02-2023,21948.97355,113405.32820,0.380675,411,13

**<h3 style="color:blue;">1.2 Convert currency amounts into numerical format.</h3>**

#### Convert 'TransactionAmount' and 'AccountBalance' columns into numeric format
#### Any invalid or non-convertible values will be replaced with NaN (missing values)

In [10]:
df["TransactionAmount" ] = pd.to_numeric(df["TransactionAmount"], errors='coerce')
df["AccountBalance"] = pd.to_numeric(df["AccountBalance"], errors='coerce')
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,3,CUST2412,ACC80131,Loan,Withdrawal,Personal Loan,Firm C,West,Manager 3,06-08-2023,33759.69057,126486.40830,0.225824,611,89
1,32,CUST1467,ACC74631,Current,Withdrawal,Home Loan,Firm D,North,Manager 2,08-11-2023,69319.19933,24834.76291,0.335717,817,174
2,9,CUST2699,ACC39482,Loan,Withdrawal,Credit Card,Firm D,West,Manager 4,15-05-2024,42831.48483,123007.43530,0.572453,332,31
3,42,CUST9535,ACC82947,Current,Withdrawal,Home Loan,Firm A,South,Manager 4,30-04-2023,70903.79697,73073.64225,0.571993,626,92
4,166,CUST7459,ACC39500,Credit,Payment,Home Loan,Firm D,South,Manager 4,16-02-2023,21948.97355,113405.32820,0.380675,411,13

#### Checking Missing

In [11]:
df.isnull().sum()

TransactionID        0
CustomerID           0
AccountID            0
AccountType          0
TransactionType      0
Product              0
Firm                 0
Region               0
Manager              0
TransactionDate      0
TransactionAmount    0
AccountBalance       0
RiskScore            0
CreditRating         0
TenureMonths         0
dtype: int64

#### **Fill missing**

In [13]:
df["TransactionAmount"] = df["TransactionAmount"].fillna(df["TransactionAmount"].median())
df["AccountBalance"] = df["AccountBalance"].fillna(df["AccountBalance"].median())

In [14]:
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,3,CUST2412,ACC80131,Loan,Withdrawal,Personal Loan,Firm C,West,Manager 3,06-08-2023,33759.69057,126486.40830,0.225824,611,89
1,32,CUST1467,ACC74631,Current,Withdrawal,Home Loan,Firm D,North,Manager 2,08-11-2023,69319.19933,24834.76291,0.335717,817,174
2,9,CUST2699,ACC39482,Loan,Withdrawal,Credit Card,Firm D,West,Manager 4,15-05-2024,42831.48483,123007.43530,0.572453,332,31
3,42,CUST9535,ACC82947,Current,Withdrawal,Home Loan,Firm A,South,Manager 4,30-04-2023,70903.79697,73073.64225,0.571993,626,92
4,166,CUST7459,ACC39500,Credit,Payment,Home Loan,Firm D,South,Manager 4,16-02-2023,21948.97355,113405.32820,0.380675,411,13

**<h3 style="color:blue;">**1.3 Validate and format date columns.</h3>**

In [15]:
df["TransactionDate"] = pd.to_datetime(df["TransactionDate"], format='%d-%m-%Y', errors='coerce')

In [16]:
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths
0,3,CUST2412,ACC80131,Loan,Withdrawal,Personal Loan,Firm C,West,Manager 3,2023-08-06,33759.69057,126486.40830,0.225824,611,89
1,32,CUST1467,ACC74631,Current,Withdrawal,Home Loan,Firm D,North,Manager 2,2023-11-08,69319.19933,24834.76291,0.335717,817,174
2,9,CUST2699,ACC39482,Loan,Withdrawal,Credit Card,Firm D,West,Manager 4,2024-05-15,42831.48483,123007.43530,0.572453,332,31
3,42,CUST9535,ACC82947,Current,Withdrawal,Home Loan,Firm A,South,Manager 4,2023-04-30,70903.79697,73073.64225,0.571993,626,92
4,166,CUST7459,ACC39500,Credit,Payment,Home Loan,Firm D,South,Manager 4,2023-02-16,21948.97355,113405.32820,0.380675,411,13

#### Convert to datetime

In [17]:
df["TransactionDate"] = pd.to_datetime(df["TransactionDate"], errors='coerce')

#### Extracted the Month and the Year

In [18]:
df['Year'] = df["TransactionDate"].dt.year.astype("Int64") #.astype("Int64") converts to integer format without decimals
df['Month'] = df["TransactionDate"].dt.month.astype("Int64")

In [19]:
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths,Year,Month
0,3,CUST2412,ACC80131,Loan,Withdrawal,Personal Loan,Firm C,West,Manager 3,2023-08-06,33759.69057,126486.40830,0.225824,611,89,2023,8
1,32,CUST1467,ACC74631,Current,Withdrawal,Home Loan,Firm D,North,Manager 2,2023-11-08,69319.19933,24834.76291,0.335717,817,174,2023,11
2,9,CUST2699,ACC39482,Loan,Withdrawal,Credit Card,Firm D,West,Manager 4,2024-05-15,42831.48483,123007.43530,0.572453,332,31,2024,5
3,42,CUST9535,ACC82947,Current,Withdrawal,Home Loan,Firm A,South,Manager 4,2023-04-30,70903.79697,73073.64225,0.571993,626,92,2023,4
4,166,CUST7459,ACC39500,Credit,Payment,Home Loan,Firm D,South,Manager 4,2023-02-16,21948.97355,113405.32820,0.380675,411,13,2023,2

**<h3 style="color:blue;">1.4 Ensure account types and transaction categories are standardized.</h3>**

In [22]:
df["TransactionType"] = df["TransactionType"].str.lower().str.strip()

# Replace variations
df["TransactionType"] = df["TransactionType"].replace({
    'cr': 'credit',
    'dr': 'debit',
    'deb': 'debit'
})

In [23]:
df["AccountType"] = df["AccountType"].str.lower().str.strip()

df["AccountType"] = df["AccountType"].replace({
    'sav': 'savings',
    'curr': 'current',
    'cc': 'credit'
})

In [24]:
df.head()

,TransactionID,CustomerID,AccountID,AccountType,TransactionType,Product,Firm,Region,Manager,TransactionDate,TransactionAmount,AccountBalance,RiskScore,CreditRating,TenureMonths,Year,Month
0,3,CUST2412,ACC80131,loan,withdrawal,Personal Loan,Firm C,West,Manager 3,2023-08-06,33759.69057,126486.40830,0.225824,611,89,2023,8
1,32,CUST1467,ACC74631,current,withdrawal,Home Loan,Firm D,North,Manager 2,2023-11-08,69319.19933,24834.76291,0.335717,817,174,2023,11
2,9,CUST2699,ACC39482,loan,withdrawal,Credit Card,Firm D,West,Manager 4,2024-05-15,42831.48483,123007.43530,0.572453,332,31,2024,5
3,42,CUST9535,ACC82947,current,withdrawal,Home Loan,Firm A,South,Manager 4,2023-04-30,70903.79697,73073.64225,0.571993,626,92,2023,4
4,166,CUST7459,ACC39500,credit,payment,Home Loan,Firm D,South,Manager 4,2023-02-16,21948.97355,113405.32820,0.380675,411,13,2023,2

In [25]:
df.to_csv("cleaned_jp_morgan.csv", index=False)